del "./pineapple_slicer_web.nw"
"C:\Program Files (x86)\WinRAR\WinRAR.exe" a -afzip "./pineapple_slicer_web.nw" "./index.html"
"C:\Program Files (x86)\WinRAR\WinRAR.exe" a -afzip "./pineapple_slicer_web.nw" "./package.json"
"C:\Program Files (x86)\WinRAR\WinRAR.exe" a -r -afzip "./pineapple_slicer_web.nw" "./css"
"C:\Program Files (x86)\WinRAR\WinRAR.exe" a -r -afzip "./pineapple_slicer_web.nw" "./js"
"C:\Program Files (x86)\WinRAR\WinRAR.exe" a -r -afzip "./pineapple_slicer_web.nw" "./img"
"C:\Program Files (x86)\WinRAR\WinRAR.exe" a -r -afzip "./pineapple_slicer_web.nw" "./res"
"C:\Program Files (x86)\WinRAR\WinRAR.exe" a -r -afzip "./pineapple_slicer_web.nw" "./fonts"
start "" "./nw-sdk/nw.exe " "./pineapple_slicer_web.nw"